# Generated by Django 5.0.6 on 2024-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hayvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('tur', models.CharField(choices=[('kopek', 'Köpek'), ('kedi', 'Kedi'), ('kus', 'Kuş'), ('diger', 'Diğer')], max_length=10, verbose_name='Tür')),
                ('cins', models.CharField(blank=True, max_length=100, verbose_name='Cins')),
                ('yas', models.PositiveIntegerField(verbose_name='Yaş')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='hayvan_resimleri/', verbose_name='Resim')),
                ('uygun', models.BooleanField(default=True, verbose_name='Uygun')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hayvan',
                'verbose_name_plural': 'Hayvanlar',
            },
        ),
    ]
