# Generated by Django 5.0.6 on 2024-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_hayvan_uygun'),
    ]

    operations = [
        migrations.AddField(
            model_name='hayvan',
            name='adres',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
