# Generated by Django 5.0.6 on 2024-05-29 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_hayvan_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='hayvan',
            name='durum',
            field=models.CharField(choices=[('Gecici Sahiplendirme', 'Geçici Sahiplendirme'), ('Barindirma', 'Barındırma '), ('Sahiplendirme', 'Sahiplendirme'), ('diger', 'Diğer')], default=django.utils.timezone.now, max_length=150, verbose_name='Durum'),
            preserve_default=False,
        ),
    ]
