# Generated by Django 5.0.6 on 2024-05-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_hayvan_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='hayvan_tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hayvan_turu', models.CharField(blank=True, max_length=55, unique=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.hayvan_tur'),
        ),
    ]
