# Generated by Django 5.0.6 on 2024-06-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_hayvan_tur_alter_hayvan_tur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hayvan_tur',
            options={'verbose_name': 'Hayvan_tur', 'verbose_name_plural': 'Hayvan_tur'},
        ),
    ]
