# Generated by Django 5.0.6 on 2024-05-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acil_durum',
            old_name='phone_number',
            new_name='telefon',
        ),
    ]
