# Generated by Django 5.0.6 on 2024-05-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_phone_number_acil_durum_telefon'),
        ('pets', '0003_hayvan_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mama_adi', models.CharField(max_length=100, verbose_name='İsim')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('stok', models.PositiveIntegerField(verbose_name='Stok')),
                ('hayvan_turu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.hayvan', verbose_name='Hayvan Türü')),
            ],
        ),
    ]
