# Generated by Django 5.0.6 on 2024-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_mama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mama',
            name='hayvan_turu',
            field=models.CharField(choices=[('kopek', 'Köpek'), ('kedi', 'Kedi'), ('kus', 'Kuş'), ('diger', 'Diğer')], max_length=20, verbose_name='Tür'),
        ),
    ]
