# Generated by Django 5.0.6 on 2024-05-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_mama_hayvan_turu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mama',
            options={'verbose_name': 'Mama', 'verbose_name_plural': 'Mamalar'},
        ),
    ]
